---
- name: antigen and oh-my-zsh
  include_role:
    name: gantsign.antigen
  vars:
    users:
      - username: "{{ the_user }}"
        antigen_libraries:
          - name: oh-my-zsh
        antigen_theme:
          name: aussiegeek
        antigen_bundles:
          - name: git
          - name: command-not-found
          - name: zsh-syntax-highlighting
            url: zsh-users/zsh-syntax-highlighting
          - name: zsh-autoswitch-virtualenv
            url: MichaelAquilina/zsh-autoswitch-virtualenv
