---

- hosts: localhost
  become: yes
  tasks:

  - name: Common CLI packages
    package:
      name:
        - unzip
        - git
        - screen
        - tree
        - vim

  - name: Common CLI networking packages
    package:
      name:
        - wget
        - curl
        - telnet
        - nmap
        - traceroute
        - net-tools
