---

- name: setup git for user
  hosts: localhost
  tasks:

  - name: ensure git is installed
    become: yes
    package:
      name: git
      state: present

  - name: copy gitconfig to user home dir
    become: no
    copy:
      src: lib/gitconfig
      dest: ~/.gitconfig
      mode: '0664'
      backup: yes
