---
- name: gantsign.antigen
  src: https://github.com/gantsign/ansible_role_antigen
  version: master

- name: markosamuli.pyenv
  src: https://github.com/markosamuli/ansible-pyenv
  version: master
