---
roles:
  - name: gantsign.antigen
    src: git@github.com:gantsign/ansible_role_antigen.git
    version: master

  - name: markosamuli.pyenv
    src: git@github.com:markosamuli/ansible-pyenv.git
    version: master
