---

- name: set up zsh for user
  hosts: localhost
  become: no
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:

    - name: install zsh
      package:
        name:
          zsh
        state:
          present

    - name: change user shell to zsh
      become: yes
      user:
        name: "{{ the_user }}"
        shell: /bin/zsh

    - name: copy zshrc to user home dir
      become: no
      copy:
        src: files/zshrc
        dest: ~/.zshrc
        mode: '0644'
        backup: yes
