---

- name: set up zsh for user
  hosts: localhost
  become: yes
  tasks:

    - name: install zsh
      package:
        name:
          zsh
        state:
          present

    - name: change user shell to zsh
      user:
        name: vagrant
        shell: /usr/bin/zsh

# make zshrc
