---
- name: Common CLI packages
  become: yes
  package:
    name:
      - unzip
      - jq
      - git
      - screen
      - tree
      - vim

- name: Common CLI networking packages
  become: yes
  package:
    name:
      - wget
      - curl
      - telnet
      - nmap
      - traceroute
      - net-tools

- name: distribution specific packages (debian/ubuntu)
  become: yes
  package:
    name:
      - ack-grep
  when: ansible_facts['os_family'] == "Debian"

- name: distribution specific packages (centos/redhat)
  become: yes
  package:
    name:
      - ack
  when: ansible_facts['os_family'] == "RedHat"

- include_tasks: tmux.yml
