---

- name: ~~~~~~~~~~ aliases ~~~~~~~~~~
  hosts: localhost
  become: yes
  tasks:

    - name: aliases file exists
      become: no
      copy:
        src: ../files/aliases
        dest: "{{ ansible_env.HOME }}/.aliases"
        force: no
        group: "{{ ansible_user_id }}"
        owner: "{{ ansible_user_id }}"
        mode: 0644

    - name: packages for "extract" function
      package:
        name:
          - bzip2
          - gzip
          - tar
          - unzip

    - name: 7zip package (debian/ubuntu)
      package:
        name:
          - p7zip-full
          - unrar
      when: ansible_facts['os_family'] == "Debian"

    - name: 7zip package (centos/redhat)
      package:
        name:
          - p7zip
          - unar
      when: ansible_facts['os_family'] == "RedHat"

    - name: bash source .aliases
      become: no
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: . ~/.aliases
        insertafter: EOF
