- name: ~~~~~~~~~~ everything ~~~~~~~~~~
  hosts: localhost
  become: no

  roles:
    - role: '../roles/git'
    - role: '../roles/zsh'
    - role: '../roles/aliases'
    - role: '../roles/vim'
    - role: '../roles/python'
    - role: '../roles/antigen'
