- name: ~~~~~~~~~~ basic ~~~~~~~~~~
  hosts: localhost
  become: no

  roles:
    - role: '../roles/git'
      tags: [ never, development ]
    - role: '../roles/zsh'
    - role: '../roles/aliases'
    - role: '../roles/vim'
