- hosts: localhost
  connection: local
  become: false

  vars:
    - pyenv_python_versions:
      - "{{ pyenv_python3_version }}"
    - pyenv_global: "{{ pyenv_python3_version }} system"

  roles:
    - role: markosamuli.pyenv

  tasks:
    - pip:
        name:
          - requests
          - ipython
          - virtualenv
