---

- hosts: localhost
  name: ~~~~~~~~~~ update system/packages ~~~~~~~~~~
  become: yes
  tasks:

  - name: update system (debian/ubuntu)
    apt:
      upgrade: dist
    when: ansible_facts['os_family'] == "Debian"

  - name: update system (centos/redhat)
    yum:
      name: '*'
    when: ansible_facts['os_family'] == "RedHat"
