---
- name: install python pre-reqs (centos/redhat)
  become: yes
  yum:
    name:
      - '@development'
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - xz
      - xz-devel
      - libffi-devel
      - findutils
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: install pyenv and python3
  include_role:
    name: markosamuli.pyenv
  vars:
    - pyenv_python_versions:
      - "{{ pyenv_python3_version }}"
    - pyenv_global: "{{ pyenv_python3_version }} system"

- pip:
    executable: "{{ ansible_env.HOME }}/.pyenv/shims/pip3"
    name:
      - requests
      - ipython
      - virtualenv
