---
- name: aliases file exists
  copy:
    src: ../files/aliases
    dest: "{{ ansible_env.HOME }}/.aliases"
    force: no
    group: "{{ ansible_user_id }}"
    owner: "{{ ansible_user_id }}"
    mode: 0644

- name: packages for "extract" function
  become: yes
  package:
    name:
      - bzip2
      - gzip
      - tar
      - unzip

- name: 7zip package (debian/ubuntu)
  become: yes
  package:
    name:
      - p7zip-full
      - unrar
  when: ansible_facts['os_family'] == "Debian"

- name: 7zip package (centos/redhat)
  become: yes
  package:
    name:
      - p7zip
      - unar
  when: ansible_facts['os_family'] == "RedHat"

- name: .aliases in .bashrc
  lineinfile:
    path: "{{ user_home }}/.bashrc"
    line: . ~/.aliases
    insertafter: EOF

- name: check whether .zshrc exists
  stat:
    path: "{{ user_home }}/.zshrc"
  register: zshrc_st

- name: .aliases in .zshrc
  lineinfile:
    path: "{{ user_home }}/.zshrc"
    line: source "$HOME/.aliases"
    insertafter: EOF
  when: zshrc_st.stat.exists
