---
- name: ensure git is installed
  become: yes
  package:
    name: git
    state: present

- name: copy gitconfig to user home dir
  become: no
  copy:
    src: ../files/gitconfig
    dest: "{{ the_user_home }}/.gitconfig"
    mode: 0664
    backup: yes

- import_tasks: git-flow.yml
  when: development_env
