colorscheme desert

set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" begin vundle plugins
Plugin 'gmarik/Vundle.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'tomtom/tcomment_vim'
Plugin 'pbrisbin/vim-mkdir'

" end vundle plugins
call vundle#end()            " required
filetype plugin indent on    " required

" plugin specific settings

au BufRead,BufNewFile *.py,*pyw set shiftwidth=4
au BufRead,BufNewFile *.py,*.pyw set expandtab
au BufRead,BufNewFile *.py set softtabstop=4

highlight BadWhitespace ctermbg=red guibg=red
au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/

syntax on
set encoding=utf-8

filetype plugin on

set ignorecase           " be case insensitive on searches
set smartcase            " but do be case sensitive on searches with capital letters
set splitright            " new vert split window to the right
set splitbelow            " new horz split window below

" Make comments bolded, light blue.  Super easy to read against a black bg.
:highlight Comment term=bold cterm=bold ctermfg=6

" don't auto comment lines
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

map <F1> <ESC>           " F1 is too close to ESC, and I use :h anyways.
map! <F1> <ESC>

"split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
