---
- name: remove system tmux
  become: yes
  package:
    name: tmux
    state: absent

- name: install required packages (centos)
  become: yes
  package:
    name:
      - libevent
      - libevent-devel
      - ncurses
      - ncurses-devel
      - automake
      - gcc
      - gcc-c++
      - make
      - bison
  when: ansible_facts['os_family'] == "RedHat"

- name: install required packages (debian)
  become: yes
  package:
    name:
      - libevent-dev
      - ncurses-base
      - ncurses-dev
      - build-essential
      - automake
      - pkg-config
      - byacc
  when: ansible_facts['os_family'] == "Debian"

- name: make tmux directory
  file:
    path: "/tmp/tmux"
    state: directory

- name: Download source
  git:
    repo: "https://github.com/tmux/tmux.git"
    dest: "/tmp/tmux"
    accept_hostkey: "no"
    version: "{{ tmux_version }}"

- name: tmux build
  command: "{{ item }}"
  args:
    chdir: "/tmp/tmux"
  with_items:
    - sh autogen.sh
    - ./configure
    - make

- name: install tmux
  become: yes
  command: "make install"
  args:
    chdir: "/tmp/tmux"

- name: copy tmux.conf to user home dir
  copy:
    src: ../files/tmux.conf
    dest: "{{ the_user_home }}/.tmux.conf"

- name: install powerline (centos)
  include_tasks: powerline-centos.yml
  when: install_powerline and ansible_facts['os_family'] == "RedHat"

- name: install powerline (debian)
  include_tasks: powerline-debian.yml
  when: install_powerline and ansible_facts['os_family'] == "Debian"

- name: check if antigen is installed
  stat:
    path: "{{ the_user_home }}/.antigen/bin/antigen.zsh"
  register: antigen_bin

- name: end playbook if antigen bin not found
  meta: end_play
  when: not antigen_bin.stat.exists

- name: install tmux zsh plugin
  command: "antigen bundle tmux && antigen apply"

- name: update zshrc to autostart tmux
  blockinfile:
    path: "{{ the_user_home }}/.zshrc"
    backup: yes
    insertbefore: BOF
    marker: "# ----- {mark} tmux plugin -----"
    block: |
      ZSH_TMUX_AUTOSTART=true
      ~/.pyenv/shims/powerline-config tmux setup
