---
# install pip if missing

- name: install powerline with pip (centos)
  pip:
    name: powerline
  when: ansible_facts['os_family'] == "RedHat"

- name: install powerline (debian)
  become: yes
  package:
    name: powerline
  when: ansible_facts['os_family'] == "Debian"

- name: powerline settings in tmux.conf
  blockinfile:
    path: "{{ the_user_home }}/.tmux.conf"
    backup: yes
    marker: "# ----- {mark} powerline settings -----"
    block: |
      # enable the powerline status bar
      run-shell 'powerline-config tmux setup'
