---
- name: ensure vim is installed
  become: yes
  package:
    name: vim
    state: present

- name: copy vimrc to user home dir
  become: no
  copy:
    src: ../files/vimrc
    dest: "{{ the_user_home }}/.vimrc"
    mode: 0664
    backup: yes

- name: vim plugins dir
  become: no
  file:
    path: "{{ the_user_home }}/.vim/plugin"
    state: directory
    mode: 0755

- name: copy vim plugins to user home dir
  become: no
  copy:
    src: ../files/plugin/
    dest: "{{ the_user_home }}/.vim/plugin/"

- name: vim indent dir
  become: no
  file:
    path: "{{ the_user_home }}/.vim/indent"
    state: directory
    mode: 0755

- name: copy vim indent to user home dir
  become: no
  copy:
    src: ../files/indent/
    dest: "{{ the_user_home }}/.vim/indent/"

- name: make vim bundle directory
  become: false
  file:
    path: "{{ the_user_home }}/.vim/bundle"
    state: directory

- name: clone vundle
  become: false
  git:
    repo: "https://github.com/gmarik/Vundle.vim.git"
    dest: "{{ the_user_home }}/.vim/bundle/Vundle.vim"
    accept_hostkey: "no"
    version: "master"

- include_tasks: vim-dev.yml
  when: development_env

- name: install vim plugins
  become: no
  command: "vim +PluginInstall +qall"
  tags:
    - skip_ansible_lint

- name: make vim default editor (bash)
  become: no
  lineinfile:
    path: "{{ the_user_home }}/.bashrc"
    line: "export EDITOR=vim"
  when: ansible_env['SHELL'] is search("bash")

- name: make vim default editor (zsh)
  become: no
  lineinfile:
    path: "{{ the_user_home }}/.zshrc"
    line: "export EDITOR=vim"
  when: ansible_env['SHELL'] is search("zsh")
